### ISSUE TITLE
eos_download fails to download TerminAttr

### ISSUE THREAD

**Issue by freedge** [arista-netdevops-community/eos-scripts#3]
from code
```
   elif "TerminAttr" in image: # if the user wants a TerminAttr image
      z = 3 # corresponds to "CloudVision" top level folder`
```

sadly it's z = 2 today. Can we have some smarter code, or a fixed format for the xml folder_tree ?
Cheers

**Comment by Sparky-python** [comment]
Issue is now fixed following an update to the website last week to remove the International EOS images top level folder. Future releases will make this more dynamic.
